# This is a basic workflow to help you get started with Actions

name: Daily Site Update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/10 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-site:
    name: Update projects page
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Setuping node v12
        uses: actions/setup-node@v1
        with:
            node-version: '12'
      
      - name: Installing gitfolio
        run: npm i gitfolio -g
      
      - name: Building profile
        run: gitfolio build Jerit3787 --theme dark --twitter Jerit3787
      
      - name: Moving config.json
        run: mv dist/config.json ..
      
      - name: Moving index.css
        run: mv dist/index.css ..
      
      - name: Moving index.html
        run: mv dist/index.html ..
    
      - name: Add & Commit to repo
        uses: EndBug/add-and-commit@v4.2.1
        with:
          add: '/'
          author_name: Jerit3787
          author_email: danish.hakim04@gmail.com
          cwd: './'
          force: true
          message: 'Daily page update'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
